image: Visual Studio 2015
stack: jdk 11

branches:
only:
  - main # ветка git

build: off # будем использовать свой скрипт сборки

install:
  - ps: $App = Start-Process -FilePath java -ArgumentList "-jar ./artifacts/app-mbank.jar" -PassThru
  - chmod +x gradlew`

build_script:
  - ps: ./gradlew test --info

on_finish:
  - ps: Stop-Process -Id $App.Idadlew test --info  # запускаем тест, флаг --info позволяет выводить больше информации